# Generated by Django 2.0.13 on 2022-03-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
            ],
            options={
                'managed': False,
                'db_table': 'confirmacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(choices=[('D', 'DNI'), ('R', 'RUC')], max_length=2)),
                ('cod_documento', models.CharField(max_length=13)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo_electronico', models.CharField(max_length=40)),
                ('password_usuario', models.CharField(max_length=32)),
            ],
            options={
                'managed': False,
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.ForeignKey(db_column='codigo_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionUsuarios.Usuario', unique=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('D', 'Desactivado')], max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.ForeignKey(db_column='codigo_empleado', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionUsuarios.Usuario', unique=True)),
                ('modalidad_trabajo', models.CharField(blank=True, max_length=1, null=True)),
                ('cargo_empleado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'empleado',
            },
        ),
    ]
