# Generated by Django 2.0.13 on 2022-03-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_categoria', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('marca_producto', models.CharField(max_length=30)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'producto',
            },
        ),
    ]
