# Generated by Django 2.0.13 on 2022-03-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('cod_promocion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio_prom', models.DateField()),
                ('fecha_fin_prom', models.DateField()),
                ('desc_precio_producto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_prom', models.CharField(max_length=3)),
                ('producto_regalo', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'promocion',
            },
        ),
    ]
